[TNL-8180] - fix wiki validation error.
openedx/olxcleaner pull request #4
Opened 2021-04-07 07:23 UTC by saadyousafarbi

### (TNL-8180)[https://openedx.atlassian.net/browse/TNL-8180]

#### Fix for validation error for UnexpectedTag for <wiki>

2021-04-07 08:44 UTC, awaisdar001 requested changes
Please add some simple test

2021-04-07 23:01 UTC, saadyousafarbi commented
@awaisdar001 test has been added. Named the new test course `testcourse13` as I already have [this](https://github.com/openedx/olxcleaner/pull/5) PR with `testcourse12` which I will merge first. 
It would be easier to rebase this way.

2021-04-08 01:04 UTC, jolyonb commented
Note that you don't necessarily need to make a new test course every time you want to add in a new test. You can add the test piece to some of the courses that already exist (particularly for cases like this, where you're just adding a new tag).

2021-04-08 07:07 UTC, awaisdar001 commented
> Note that you don't necessarily need to make a new test course every time you want to add in a new test. You can add the test piece to some of the courses that already exist (particularly for cases like this, where you're just adding a new tag).

I think that makes sense @saadyousafarbi we can also tweak existing testcourses for cases that are possible.

2021-04-08 07:08 UTC, awaisdar001 commented on testcourses/testcourse13/course/mycourseurl.xml
> +  <wiki slug="test_wiki_slug"/>
Just add this piece of code in some other test course and we are good to go.

2021-04-08 07:09 UTC, awaisdar001 commented on tests/test_validate.py
> +def test_validate_course13():
`test_wiki_xblock_is_supported`

2021-04-08 10:53 UTC, jolyonb commented on tests/helpers.py
> +            raise ValueError("Error not found")
I think the error message is wrong?

2021-04-08 11:32 UTC, awaisdar001 approved these changes

2021-04-08 11:44 UTC, merged